[package]
name = "sumic"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
libsumi = { path = "../libsumi" }
naga = { version = "28.0.0", features = ["glsl-in", "msl-out", "spv-out", "wgsl-out"] }
